### ISSUE TITLE
Dynamic namespaces in Java templates

### ISSUE THREAD

**Issue by davgordo** [contract-first-idp/software-templates#15]
Current Java templates do not use form input to determine namespaces and organize Java source code. The form input should affect the source code scaffolding.

Current Java templates have an issue where a user input string such as `com.acme.integration` cannot be easily used in Java source code scaffolding which would sort sources into directories accordingly. Let's create a convention in Developer Hub templates so that the user provides a more granular input, for example `com`, `acme`, and `integration` separately. 

In many organizations, the choices for top-level organization domain may be limited to a small set.

**Comment by rohit-taneja-redhat** [comment]
Working on the issue
